### ISSUE TITLE
JQuery Issue

### ISSUE THREAD

**Issue by darman89** [krakendio/krakend-documentation#174] opened 2022-10-03 14:40 UTC
Hi there,

First of all, thank you a lot for the Krakend project. I like to mention an issue regarding JQuery load in docs pages. When my browser (No-Cache mode) loads the page (e.g., https://www.krakend.io/docs/overview/), it comes with the following error in the console:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://code.jquery.com/jquery-3.6.0.min.js.
`
**User-Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0

![image](https://user-images.githubusercontent.com/4751990/193605046-3fde16de-5115-4861-96e7-934cdebe4408.png)

The above problem affects all of the dropdown menu access. 

Thanks in advance and sorry for my English.

**Comment by alombarte** [comment] 2022-10-04 17:10
Hello @darman89 ,

I tested with Firefox, but I don't see this error in the console log and the dropdown works correctly.

We will investigate further

**Comment by obokaman-com** [comment] 2022-10-04 17:57
Hi @darman89, thanks for the detailed feedback!

We're not forcing a `Same Origin` policy for CORS. I see other external resources being loaded correctly (from g2crowd.com or fonts.googleapis.com, for instance), so it seems something unique to scripts loaded from `code.jquery.com`

You perhaps have an ad blocker extension enabled that could block that request or origin. A failure in the certificate of the script's origin server could also cause this error, although it sounds unlikely to me. 🤔

Could you please confirm if it also happens when you disable the extensions you are currently using?

Thanks for your collaboration, and sorry for the inconvenience.

**Comment by darman89** [comment] 2022-10-04 19:51
Hi @alombarte and @obokaman-com, thank you very much for your comments.

Although yesterday the problem persisted for me throughout the day, even in Google Chrome - sadly, I don't have any screenshots of this; today, I was able to visit the Krakend documentation pages without problems - no changes or updates in my browsers. 

![image](https://user-images.githubusercontent.com/4751990/193907265-749082a1-1519-4327-bd6a-95d047dd6113.png)

Maybe have been a particular issue and not a general situation. Please feel free to close this issue if you see fit, as although yesterday the documentation was inaccessible, today I was able to access it without problems.

Again, thank you very much for your kind replies, and sorry for the inconvenience. Krakend is an excellent project.

P.S. Sorry for my English.

**Comment by alombarte** [comment] 2022-10-05 08:31
I couldn't reproduce this. The website has not changed its JS in more than a year.

If you find it again, please let us know. Meanwhile, I am closing this as I have no way to see it happening.

Thank you very much for reporting and your kind words

**Closed by alombarte** 2022-10-05 08:31 UTC
